# Command Line Raguments in config.yaml
dataset: /Data/ir256_rgb512
epochs: 120
batch_size: 4
ir_size: 256
rgb_size: 512
lr: 0.0001
weight_decay: 0.0
optimizer: adamw
lr_warmup: 0
workers: 4
base_channels: 64
model_type: gan_unet
adv_weight: 0.01
fm_weight: 10.0
loss_type: v3
checkpoint_dir: ./checkpoints
resume: ''
save_freq: 5
seed: 42
exp_run_name: exp_gannet_3
gpu: 0,1
amp: true
grad_checkpoint: false
grad_accum: 2
lpips_freq: 5
warmup_epochs: 0
d_lr: 0.0001
gan_warmup_epochs: 0
cosine_T0: 30
multi_kernel: false
grad_clip: 1.0
perceptual_weight: 0.1